### ISSUE TITLE
agent: when restarting server, agent hangs when accepting new connections

### ISSUE THREAD

**Issue by nl5887** [honeytrap/honeytrap#111]

**Comment by skamoen** [comment]
It seems like a timing issue, wasn't able to track down the cause. It's not consistent and doesn't fail on the same place.

While the agent is pinging, connections are accepted but it (sometimes?) hangs when the service tries to read from the connection. After repeated connects the agent eventually also stops pinging. New sessions are still established at that point but the service always hangs at reading the connection.

**Comment by skamoen** [comment]
A more systematic approach resulted in the following:

1. _Server started first, then agent_: No issues
2. _Server started first, then agent. Restart server_ : Agent reconnects and starts pinging. Agent picks up connections. Server handles connections from agent, but service seems to hang on connection reads.
3. _Server started first, then agent, restart server, restart agent_: No issues
4. _Agent started first, then server_: No issues
5. _Agent started first, then server, then restart agent_: No issues

I'm starting to doubt the assumption it's a serverside bug. To be continued...
