### ISSUE TITLE
Load configuration file from system path

### ISSUE THREAD

**Issue by athos-ribeiro** [honeytrap/honeytrap#195]
As pointed in #136, it would be nice to have honeytrap to also look for a configuration file in a [FHS](http://www.pathname.com/fhs/) compatible path. This would allow honeytrap system installations, like installing it from distriburion packages, like .deb or .rpm.

`/etc/honeytrap/config.toml` seems to be a good start. To avoid backwards incompatibility, it could either look for the file in the current work dir (this is the default right now) and fall back to the system path if it cannot find the file, or do the opposite, looking in the system path first and then falling back to the current directory.

**Comment by nl5887** [comment]
Currently we can use the ```--config`` to define the location of the config file. Would that be sufficient?
