### ISSUE TITLE
Getting an Unhealthy Kibana error

### ISSUE THREAD

**Issue by jcbeaub** [honeytrap/honeytrap#197]
Upon trying to install honeytrap I keep getting this error and would like some advice on fixing it:

Status: Downloaded newer image for docker.elastic.co/kibana/kibana:5.6.4
Starting honeytrap_elasticsearch_1 ... done
Starting honeytrap_honeytrap_1 ... done

ERROR: for kibana  Container "0c544c9b35fe" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by nl5887** [comment]
@jcbeaub do you see anything in the logs? 

`docker log honeytrap_kibana_1`?

**Comment by jcbeaub** [comment]
@nl5887 
![image](https://user-images.githubusercontent.com/32201168/36735584-898ce24e-1ba4-11e8-9ae1-8e1698831b0d.png)
This is what i get from that command, i got this on my laptop as well and my friend also is getting the same message.

**Comment by nl5887** [comment]
hmm, could you verify that elasticsearch has been started (`docker info honeytrap_elasticsearch_1`)

**Comment by jcbeaub** [comment]
Couldn't get that exact command working but took a large number of screen-shots with related info:

![docker images](https://user-images.githubusercontent.com/32201168/36744846-d7066394-1bbb-11e8-8ceb-059d3e5843cd.png)
![docker log elastic](https://user-images.githubusercontent.com/32201168/36744850-d866a640-1bbb-11e8-9c52-7e49526f99b6.png)
![docker ps](https://user-images.githubusercontent.com/32201168/36744853-d9eed898-1bbb-11e8-9c0b-5545e9a522f7.png)
![elasticsearch1](https://user-images.githubusercontent.com/32201168/36744857-dc6edc3a-1bbb-11e8-9d38-0089b0a863ea.png)
![honeytrap fail 1](https://user-images.githubusercontent.com/32201168/36744860-ddbc6b84-1bbb-11e8-816a-3ffc55223b3f.png)
![honeytrap running](https://user-images.githubusercontent.com/32201168/36744863-dee09d6e-1bbb-11e8-8570-c021bc3cc40f.png)
![honeytrap running 2](https://user-images.githubusercontent.com/32201168/36744864-dfed0490-1bbb-11e8-8bf0-f578b028265a.png)
![honeytrap stopping](https://user-images.githubusercontent.com/32201168/36744866-e123b84a-1bbb-11e8-96b5-9171855d1638.png)

**Comment by nl5887** [comment]
Elasticsearch is not starting, because the data folder has incorrect permissions. Try to `chown -R 1000:1000` your data folder. Uid 1000 is the default uid for docker.

**Comment by jcbeaub** [comment]
@nl5887 I was able to get honeytrap fully working and even logging my cowrie honeypot, but how do I make honeytrap a high interaction honeypot and not a logging proxy?

**Comment by nl5887** [comment]
LXC support won't work from within Docker, so you need to install it without. Make sure LXC has been installed and build Honeytrap using:

```
$ go build -tags="lxc" ...
```

Next you can use this documentation: http://docs.honeytrap.io/docs/config/directors/lxc/. Please let me know if you run into issues, so the documentation can be updated.

**Comment by nl5887** [comment]
@jcbeaub welcome. It seems you didn't compile the binary using:

```
$ go build -tags="lxc" ...
```

That will probably fix both errors.

**Comment by nl5887** [comment]
@jcbeaub any updates on this issue?

**Comment by nl5887** [comment]
Closing this issue, please let me know if you've still issues.
