### ISSUE TITLE
Can I add GPLv3 code?

### ISSUE THREAD

**Issue by CapacitorSet** [honeytrap/honeytrap#203]
I'd like to integrate [sinksmtp](https://github.com/siebenmann/sinksmtp) into the codebase as a SMTP service, but it is under a GPLv3 license. Is it okay? If yes, how would I go about the license header, would I use only the sinksmtp license or both the sinksmtp GPLv3 and the honeytrap AGPLv3?

**Comment by CapacitorSet** [comment]
I'm not a license expert, but I think it would be legally okay to include sinksmtp into the codebase (because the software must be redistributed under a compatible license, and the AGPL is compatible with the GPL), and the copyright notice would use both honeytrap's AGPL and sinksmtp's GPL.

**Comment by nl5887** [comment]
I think that won't be a problem, but have you seen the PR I just merged? It supports SMTP already, so maybe it will be sufficient for you to take this one as base.

**Comment by CapacitorSet** [comment]
I just saw the PR, at a quick glance it seems rather complete so there's no point in redoing it.

Thanks for the clarification!
