### ISSUE TITLE
Generate container names using other format

### ISSUE THREAD

**Issue by nl5887** [honeytrap/honeytrap#22]
* based on 
https://github.com/kubernetes/kubernetes/blob/c14fa94a4a7d12dd382ea7296a81ab9647954362/staging/src/k8s.io/client-go/pkg/api/v1/generate.go#L59
* current md5 chars are too long and will give warnings
* use format {template}-{unique}
* it would be great if it is a one way hash based on originating ip address

**Comment by influx6** [comment]
I just wrote a new library built specifically for us which will allow us create naming convention generators easily based on the sample code you provided. It is abit of copy on the idea from that code which is great. We can take the core concept which I changed abit and created standard namers for use.

https://github.com/honeytrap/namecon.

We simply need to decide what crypto package we will use to create the unique hashes based on originating ip as discussed.
