### ISSUE TITLE
config: ports: support multiple configs of ports

### ISSUE THREAD

**Issue by nl5887** [honeytrap/honeytrap#306]
it would be nice to allow

```
ports=["tcp/11211", "udp/11211"]
```

**Comment by CapacitorSet** [comment]
Would you prefer supporting both `port="tcp/11211"` and `ports=["tcp/11211", "udp/11211"]` or only the latter syntax?

**Comment by nl5887** [comment]
both will be very nice, that prevents a lot of errors.
