### ISSUE TITLE
Running 'dep ensure' will undo the work done in netstack.

### ISSUE THREAD

**Issue by sammynx** [honeytrap/honeytrap#358]
I ran ```dep ensure``` after commit 24428ae9943e9f7c7365f663d0614c2b33bc936b and can't build master anymore due to a fresh *netstack* install.

**Comment by nl5887** [comment]
fixed with #364

**Comment by nl5887** [comment]
what is important btw, is to use the latest dep version. They are supporting a `source` directive now in the Gopkg.lock file, indicating it should use a different source (the fork).
