### ISSUE TITLE
Directors Refactor and Interface.

### ISSUE THREAD

**Issue by influx6** [honeytrap/honeytrap#40]
# Why
We wish to reason about a new system where the director is abstracted into a common interface for all vms and emulators to implement, this will directly allow us to work with other platforms apart from lxc such as docker,etc.

## Reason: 
As part of our plans detailed in the [API Plans](https://github.com/honeytrap/honeytrap/wiki/API-Plans) page, we want to focus solely on the first point on abstracting out the directory.
```
Honeytrap should support usage of emulators apart from lxc containers, possible with 
vms that make it possible for us to target IOT platforms and architecture, which will 
require abstracting the director.
```

## Brief
Since we want to support other emulators/vms, then lets reason how the current director works and what we need to actually support the other emulators, since we will need:

- A consistent interface for all directors to implement.
- A grasp of the different implementation details of the current director, how it works and what is specific to lxc that we know is required in other platforms which helps us create a generic method contract through the interface.
- What platforms we need to initially support.

**Comment by nl5887** [comment]
* we should be able to have a different application/emulator per service or services combined (eg just a simple http honeypot) or existing honeypots
* we should be able to use lxc (like we do now), but also use virtual machines (hyper v / kvm).

**Comment by influx6** [comment]
@nl5887 What type of functionality must a generic director provide us to allow us use different vms?

**Comment by influx6** [comment]
The initial step is as always to come up with a central minimal interface that must be met by all directors. I think we need to pick one between hyper v or kvm then see what packages are available to interface with it. 

With this we can draw a common interface for which all directors must implement plus it will allow us sharpen the target.

**Comment by influx6** [comment]
Secondly, am still not sure what we mean by services. Do we mean the ssh or http proxies?

If so, how does each work towards the target of a honeypot. I can easily grasp how a ssh proxy allows us to have sessions for users but am yet unsure how sip/http work and how users related with those containers through those services?

**Comment by influx6** [comment]
Your thoughts @nl5887

**Comment by influx6** [comment]
Remco:

```
The services are in deed all kind of protocols, http, ssh, etc

Http will work the same as ssh, there is already a proxy for it within the repo, so when honeytrap receives a request on a listening port, it will ask the director to setup a proxy for remote address, local address, remote port and local port. This way the director will look up if it needs to start a container or something different, and return a connection that connection will be used for proxying.

```
