### ISSUE TITLE
No public key when starting docker-compose script

### ISSUE THREAD

**Issue by crypsys** [honeytrap/honeytrap#414]
I'm fairly new to this, sorry if it's just idiocy,  I compiled the Agent and followed the server install instructions. I'm running Ubuntu 16.04 and when I try to run the agent I can't because I don't have the public key.

When I run the following to start honeytrap server:

`docker-compose -f ./docker-compose-honeytrap.yml up`

I don't see the following message in the output per the documentation:
`honeytrap_1      | HoneyTrap Agent Server public key: <key>`

The only message I get referring to keys is:
`honeytrap_1      | 08:59:59.922 honeytrap/server  WARN 008 Unrecognized keys in configuration: [service.telnet.image service.telnet.server-name]`

When I look in here the following location, there appears to be no documentation:
[(http://docs.honeytrap.io/docs/concepts/framework/honeytrap-server/)](http://docs.honeytrap.io/docs/concepts/framework/honeytrap-server/)

The honeytrap server appears to initialize successfully: 

honeytrap_1      | 2018/08/10 08:59:59 Using config file /config/config.toml
honeytrap_1      | Honeytrap starting (bdmxxxxxxxxbcbgi0)... 
honeytrap_1      | Version: 2018-08-01T18:49:21Z (1b595a78e1da)
honeytrap_1      | 08:59:59.913 honeytrap/server ▶ DEBU 002 Using datadir: /data
honeytrap_1      | 08:59:59.917 honeytrap/server ▶ INFO 003 Configured service ssh-simulator (ssh-simulator)
honeytrap_1      | 08:59:59.918 honeytrap/server ▶ INFO 004 Configured service telnet (telnet)
honeytrap_1      | 08:59:59.918 honeytrap/server ▶ INFO 005 Configured port tcp/:8022
honeytrap_1      | 08:59:59.920 honeytrap/server ▶ INFO 006 Configured port tcp/:8023
honeytrap_1      | 08:59:59.921 honeytrap/server ▶ INFO 007 Configured port tcp/:5900
honeytrap_1      | 08:59:59.922 honeytrap/server ▶ WARN 008 Unrecognized keys in configuration: [service.telnet.image service.telnet.server-name]
honeytrap_1      | 08:59:59.923 listeners/socket ▶ INFO 009 Listener started: tcp/:8022
honeytrap_1      | 08:59:59.926 listeners/socket ▶ INFO 00a Listener started: tcp/:8023
honeytrap_1      | 08:59:59.926 listeners/socket ▶ INFO 00b Listener started: tcp/:5900
honeytrap_1      | 08:59:59.945 web ▶ INFO 00c Web interface started: 127.0.0.1:8089

Thanks for any help, it looks like a great project

**Comment by CapacitorSet** [comment]
I think the [`config-docker.toml`](https://github.com/honeytrap/honeytrap/blob/master/config-docker.toml) file is wrong; it should say `type="agent"` at line 2.

Can you retry with this change?

**Comment by crypsys** [comment]
That fixed it thanks. I don't know if it is related but the documentation on the honeytrap.io has a 404 on the config-docker.toml file. The docker-compose-honeytrap.yml is ok.

`wget https://gist.githubusercontent.com/Coen-Schuijt/0600aca75dc99f6c2ce2c260ad00f0ab/raw/config-docker.toml`

On this page:
`https://docs.honeytrap.io/docs/setup/server/setup-prerequisites/`

I pulled the config-docker.toml file from the update GitHub file instead, perhaps I would still have had to change it anyway from the dead link. I'm fairly new at all this so I'm bumbling about a bit but it's up and running to a base config now. Thanks!

**Comment by CapacitorSet** [comment]
It's fine, the documentation is still "rough around the edges", but afaik there's one person working on it.

I'll fix this, and open an issue in honeytrap-docs.

**Comment by crypsys** [comment]
what you have is actually very good. I'm up and running on Ubuntu with only a minor Agent issue just by following the docs. Thanks again.
