### ISSUE TITLE
question about honeytrap server deploy

### ISSUE THREAD

**Issue by VLiBai** [honeytrap/honeytrap#424]
Hello，the honeytrap project is interesting。I'm trying to deploy a hoenytrap，but I don't know how to solve some question。
I find the architecture at http://docs.honeytrap.io/docs/concepts/framework/architecture/ ，how can I deploy the honeytrap server If I want to deploy according to this architecture，I noticed that listener type option in the server configuration file is different for the agent and the sensor，so how to config the listener type in alone server config file , or I have to deploy two server at least and then collect the attack data to another Raven？

**Comment by martijnjanssen** [comment]
For your first deployment of honeytrap, just deploying a honeytrap-server is the easiest, so without any agents. From there you can see what you actually need, you can change the setup at any point.

To be honest, your question is not very clear. It sounds to me like you want to exactly replicate the setup in the first image of the "architecture" page, but I could be wrong. What is your exact question?

It's also better to ask these questions in the https://groups.google.com/forum/#!forum/honeytrap-users mailing list, it's a better place for these types of questions and you'll get faster responses.

**Comment by CapacitorSet** [comment]
The most minimal setup you can run is a "standalone server", for which you would use listener="server" ([example](https://github.com/honeytrap/honeytrap-configs/blob/master/server-standalone/config-server-standalone.toml)). A server can receive requests directly.

You can collect the attack data to Raven if you wish, but it's not necessary. You can also just print it to the console, or save it to a file, or any combination, depending on what filters and channels you configure.

Il 16 agosto 2018 04:11:36 GMT-04:00, LiBai <notifications@github.com> ha scritto:

**Comment by VLiBai** [comment]
Thank you , I mean, can one honeytrap  server  receive data from different kinds of clients, such as sensor,agent

**Comment by VLiBai** [comment]
@martijnjanssen You are right. I want partial reduction the first image of the architecture page. For a short, my question is , Can the one honeytrap server receive the different clients, such as honeytrap-agent client,honeytrap-sensor client. If so, how to write [listener] in the honeytrap server config file.

Thank you,I will use the google mail list next time.

**Comment by martijnjanssen** [comment]
If you want to deploy to only one server, a single instance of honeytrap is enough with a config that is similar to the template.

If you want a central honeytrap server to which several other honeytrap-agents are forwarding connections to, you should take a look at https://github.com/honeytrap/honeytrap-agent. Honeytrap agent retrieves the config file from the honeytrap server and forwards incoming connections to the central honeytrap server.
This does require you to change the listener type of the central honeytrap server to type="agent". This means that the central honeytrap server only needs the agent connection port open (I believe 1339 by default) and no longer directly receives outside connections to services.

**Comment by VLiBai** [comment]
OK,understand.
