### ISSUE TITLE
Warnings thrown for used keys in config

### ISSUE THREAD

**Issue by martijnjanssen** [honeytrap/honeytrap#425]
There are some incorrect warning messages for keys like: `capture` and `file.filename` in the config. Reporting the values are unused, which is not the case. The warnings are originating from the line added at `honeytrap.goR399` in #319. 

Maybe some race conditions, although it could also be that the `Undecoded()` method doesn't work as expected.

**Comment by CapacitorSet** [comment]
It is a known issue (#402). It was fixed in #407, which is waiting to be merged.

**Comment by martijnjanssen** [comment]
Ah no problem, I didn't look at that PR since the name didn't look associated with my issue. I'll close this as it is already close to done. :+1:
