### ISSUE TITLE
Separate configs for agents

### ISSUE THREAD

**Issue by doshmajhan** [honeytrap/honeytrap#428]
Was wondering if there was a wag to have separate configs for different agents, to say have one agent be running a ssh simulator, and another agent be running vnc, etc. Wasn't seeing much in the docs around that area it looked like every agent has to use the same config.toml file from the server.

**Comment by CapacitorSet** [comment]
I worked on that [here](https://github.com/CapacitorSet/honeytrap/tree/feat-config-per-agent), if someone wants to merge it it's a matter of:
 * cleaning up the code (removing debug statements);
 * merging [my commit in honeytrap-agent](https://github.com/CapacitorSet/honeytrap-agent)
 * merging `feat-config-per-agent`.

I would do that, but I've currently given up on contributions while I wait for the rest of my PRs to be merged.

**Comment by doshmajhan** [comment]
Yea that is exactly what I was looking for, thanks for the referral. Will try building off of those branches, and keep an eye out if they make any progress on merging those PR's. Thanks for the help!

**Comment by nl5887** [comment]
We're behind with many pull requests, but that's because many interesting features will follow. Thanks for using Honeytrap and join our [Google groups](https://groups.google.com/forum/#!forum/honeytrap-users).
