### ISSUE TITLE
desktop.png for VNC service

### ISSUE THREAD

**Issue by doshmajhan** [honeytrap/honeytrap#429]
I was wondering if there was a example desktop.png that works with the VNC service. I added my own, and whenever a VNC connection is received the server throws this error in a loop 
``21:26:07.428 services/vnc ▶ ERRO 7b83d unsupported inRange: v=65535, max=255`` 
Seems to be stemming from ``inRange`` within ``pushGenericLocked`` within ``/services/vnc/rfb.go``

**Comment by nl5887** [comment]
![screenshot-20171030174349](https://user-images.githubusercontent.com/3748903/45616647-6c3f6e80-ba70-11e8-89f1-734eedb08976.png)

This is one I used before.
