### ISSUE TITLE
Seperate components like git

### ISSUE THREAD

**Issue by nl5887** [honeytrap/honeytrap#45]
make a honeytrap binary that will start subprocesses like:

* honeytrap server will start honeytrap-server
This is the base server

* honeytrap cli wil start honeytrap-cli
This will show all information regarding running containers and attackers and such.

**Comment by influx6** [comment]
## Questions

1. For `Honeytrap Server` is the base server we have running when lunching the honeytrap `main.go` file?

2. For `Honeytrap CLI` as to containers and attack information, are we already gathering this data and storing them internally?

**Comment by influx6** [comment]
We wish to expose certain commands which allows us to retrieve specific information from running instance.

- `honeytrap lxc ls`
This command will allow us detail existing running containers based on deployed provider, which will inform of running containers and attached IPs and data transmitted if possible.

-`honeytrap lxc kill`
This command will allow us to abruptly stop a running container with our deployed server.

-`honeytrap lxc rm`
This command will allow us to remove an existing container from all available created containers.

- `honeytrap lxc create`
This command will allow us to create a container with an existing lxc containers.
