### ISSUE TITLE
licensing unclarity

### ISSUE THREAD

**Issue by armijnhemel** [honeytrap/honeytrap#467]
I saw that in c0d81e0e8667c1187d473754adfd936db25da6a1 many files were relicensed from AGPL 3 to Apache 2. However, there are still a few places that say AGPL, so I was wondering what the actual license is. In particular:

    README.md

and

     vendor/github.com/honeytrap/protocol/decoder.go

As AGPL 3 and Apache 2 are compatible the end result would be AGPL 3 for any binary containing decoder.go.

**Comment by nl5887** [comment]
license for honeytrap/protocol and readme has been updated
