### ISSUE TITLE
SSH simulator run commands

### ISSUE THREAD

**Issue by kounelios13** [honeytrap/honeytrap#492]
Hello.I have a question.WHen testing the ssh simulator i noticed the following thing.After authenticating and going to the custom terminal (ubuntu 16) I always get a "command not found" for everything I type.Is there a way to declare some basic commands that a user might be able to run in the ssh simulator?

**Comment by sammynx** [comment]
Currently this is not an option. All input gets a `command not found` reply. Except `exit` which exits the session.

**Comment by kounelios13** [comment]
Is there any way to currently achieve this?

**Comment by sammynx** [comment]
There is still no option to do this.
