### ISSUE TITLE
log file timeout?

### ISSUE THREAD

**Issue by villain** [honeytrap/honeytrap#505]
i have the following in my config:

```
[channel.file]
type="file"
filename="/opt/honeytrap/log/honeytrap.log"
maxsize=536870912
timeout="1h"
```

however honeytrap complains about the key channel.file.timeout

```
17:15:42.192 honeytrap/server ▶ WARN 018 Unrecognized keys in configuration: [channel.file.timeout]
```

can someone advise what i've done incorrectly?

**Comment by sammynx** [comment]
`timeout` is not a configuration option for the file channel. File rotation is only based on `maxsize`. If you remove the line it should be ok.

It's in the documention I noticed, but this is a mistake. I created an issue about it there, https://github.com/honeytrap/honeytrap-docs/issues/71 and closing this one.
