### ISSUE TITLE
Events from HoneyTrap to ELK (standalone)

### ISSUE THREAD

**Issue by RoxyBroge** [honeytrap/honeytrap#507]
I use HoneyTrap Playground. 
In the same time i have standalone ELK (with authentication).
I want receive event from honeytrap to standalone ELK. 
How can i do it?
Where enter credentials in Honeytrap?

**Comment by lukemilby** [comment]
@RoxyBroge 
In the HoneyTrap config were you setup your elasticsearch server you will need to add

```
username="**USERNAME HERE**"
passoword="**PASSWORD HERE**"
```
example:
```
[channel.elasticsearch]
type="elasticsearch"
url="http://elasticsearch:9200/honeytrap"
username="root"
passoword="secret"
```

**Comment by sammynx** [comment]
I suppose this is answered.
